   
#======================================
# Zuul Parameters
#======================================

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000  
  prefix: /api
  stripPrefix: true
  ignoredServices: '*'
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  
#======================================
# Route Parameters
#======================================
  routes:
    auth:
      path: /**
      serviceId: authservice
      sensitive-headers: Cookie, Set-Cookie
    users:
      path: /user/**
      serviceId: user-service
      sensitive-headers: Cookie, Set-Cookie  
    emailreg:
      path: /registration/**
      serviceId: registration-service
      sensitive-headers: Cookie, Set-Cookie 
   
authservice:
  ribbon:
    ConnectTimeout: 20000
    ReadTimeout: 60000
    MaxConnectionsPerHost: 100
    MaxTotalHttpConnections: 500

user-service:
  ribbon:
    ConnectTimeout: 20000
    ReadTimeout: 60000
    MaxConnectionsPerHost: 100
    MaxTotalHttpConnections: 500
    
registration-service:
  ribbon:
    ConnectTimeout: 20000
    ReadTimeout: 60000
    MaxConnectionsPerHost: 100
    MaxTotalHttpConnections: 500
    
hystrix:
  command:    
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 160000
            


#================================================================
#Eureka properties
#================================================================    
eureka:
  instance:
    #intervallo di attesa prima della rimozione del servizio(def 90 sec)
    lease-expiration-duration-in-seconds: 60
    #intervallo invio heartbeat (def 30 sec)
    leaseRenewalIntervalInSeconds: 15
    #id di idendificazione dell'istanza
    instanceId: ${server.port}-${spring.application.name}
    #registrazione per indirizzo ip (def hostname)
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://admin:admin@localhost:8761/eureka/}
    eureka-server-connect-timeout-seconds: 8  
           
# ==============================================================
# = Log configuration
# = default levels ERROR, WARN, INFO
# = levels TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
# ==============================================================
logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        security: DEBUG
  file: 
    name: ./logs/${spring.application.name}.log
    max-size: 1MB
  pattern:
    file: "%d{ dd-MM-yyyy } [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


        
# ==============================================================
# = Actuator configuration
# ==============================================================        
# info
info:
  nome:
    nome-app: "Zuul Server"
  assistenza:
    mail: daniel199604@hotmail.it
    nome: Daniele Tomasello
    telefono: 3203063609
#config
management:
  endpoint:
    health:
      #show-details: WHEN_AUTHORIZED
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,routes,filters
  info:
    git:
      mode: full
        
        
#================================================================
#Sicurezza properties
#================================================================           

jwt:
  header: X-Auth
  refreshHeader: X-Refresh
  expiration: 30
  refreshExpiration: 1800
  secret: mySecret     


  
      