
       
#======================================
# Zuul Parameters
#======================================

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000
  ignored-services: '"*"'
  prefix: /api
  
#======================================
# Route Parameters
#======================================
  routes:
    auth:
      path: /**
      sensitive-headers: Cookie,Set-Cookie
      service-id: authservice
  strip-prefix: true    
    
authservice:
  ribbon:
    connectTimeout: 20000
    maxConnectionsPerHost: 100
    maxTotalHttpConnections: 500
    readTimeout: 60000
hystrix:
  command:
    authservice:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 90000    

#================================================================
#Eureka properties
#================================================================    
eureka:
  client:
    eureka-server-connect-timeout-seconds: 8
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://admin:admin@localhost:8761/eureka/}

            
#================================================================
#Livello Log di Sicurezza
#================================================================            
logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        security: DEBUG
#================================================================
#Sicurezza properties
#================================================================           

jwt:
  header: 'X-Auth'
  expiration: 7200
  secret: 'mySecret'        


  
