
#======================================
# Zuul Parameters
#======================================

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000  
  prefix: /api
  stripPrefix: true
  ignoredServices: '*'
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  #Access-Control-Allow-Credentials,
  
#======================================
# Route Parameters
#======================================
  routes:
    auth:
      path: /**
      serviceId: authservice
      sensitive-headers: Cookie, Set-Cookie
    users:
      path: /guestUser/**
      serviceId: user-service
      sensitive-headers: Cookie, Set-Cookie    
    
authservice:
  ribbon:
    ConnectTimeout: 20000
    ReadTimeout: 60000
    MaxConnectionsPerHost: 100
    MaxTotalHttpConnections: 500
    NIWSServerListClassName : com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers : http://localhost:8081

user-service:
  ribbon:
    ConnectTimeout: 20000
    ReadTimeout: 60000
    MaxConnectionsPerHost: 100
    MaxTotalHttpConnections: 500
       
    
hystrix:
  command:
    user-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 90000
    authservice:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 90000
           

 
   

#================================================================
#Eureka properties
#================================================================    
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://admin:admin@localhost:8761/eureka/}
    eureka-server-connect-timeout-seconds: 8  

            
#================================================================
#Livello Log di Sicurezza
#================================================================            
logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        security: DEBUG
#================================================================
#Sicurezza properties
#================================================================           

jwt:
  header: 'X-Auth'
  expiration: 7200
  secret: 'mySecret'        


  
